### ISSUE TITLE
`ValueError: RGBA values should be within 0-1 range`

### ISSUE THREAD

**Issue by abrichr** [microsoft/SoM#25]
If mask alpha > .85 and granularity > 2.7, inference fails with the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 230, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1590, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1176, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/src/app/./demo_som.py", line 114, in inference
    output, mask = inference_sam_m2m_auto(model, _image, text_size, label_mode, alpha, anno_mode)
  File "/usr/src/app/task_adapter/sam/tasks/inference_sam_m2m_auto.py", line 50, in inference_sam_m2m_auto
    demo = visual.draw_binary_mask_with_number(mask, text=str(label), label_mode=label_mode, alpha=alpha, anno_mode=anno_mode)
  File "/usr/src/app/task_adapter/utils/visualizer.py", line 1156, in draw_binary_mask_with_number
    self.draw_polygon(segment, color=color, edge_color=edge_color, alpha=alpha)
  File "/usr/src/app/task_adapter/utils/visualizer.py", line 1228, in draw_polygon
    edge_color = mplc.to_rgb(edge_color) + (1,)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/colors.py", line 514, in to_rgb
    return to_rgba(c)[:3]
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/colors.py", line 302, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/colors.py", line 405, in _to_rgba_no_colorcycle
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range
```

<img width="1511" alt="image" src="https://github.com/microsoft/SoM/assets/774615/4fb8db5a-6e42-44cb-bc27-e85b413348c6">

<img width="1512" alt="image" src="https://github.com/microsoft/SoM/assets/774615/6011e815-a9ca-4734-882f-ade91d2f89dd">

**Comment by jwyang** [comment]
thanks! @abrichr , did you figure out the solution?

**Comment by abrichr** [comment]
Not yet, we are working around this for now by keeping mask_alpha at 0.8 and granularity at 2.7.

However, based on the stack trace, it seems that `edge_color` should be clamped before the call to `mplc.to_rgb` in https://github.com/microsoft/SoM/blob/80695e53fa5d002f997f8beb0fd4e2ae449213f1/task_adapter/utils/visualizer.py#L1228 .

**Comment by abrichr** [comment]
Confirmed working:
```
diff --git a/task_adapter/utils/visualizer.py b/task_adapter/utils/visualizer.py
index bd78a98..7362b4b 100644
--- a/task_adapter/utils/visualizer.py
+++ b/task_adapter/utils/visualizer.py
@@ -1225,6 +1225,7 @@ class Visualizer:
                 edge_color = self._change_color_brightness(color, brightness_factor=-0.7)
             else:
                 edge_color = color
+        edge_color = tuple(min(c, 1) for c in color)
         edge_color = mplc.to_rgb(edge_color) + (1,)
 
         polygon = mpl.patches.Polygon(
```
