### ISSUE TITLE
could not quick start install the program 

### ISSUE THREAD

**Issue by Alexyuanfun** [microsoft/SoM#26]
It shows this error:
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
      Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
      Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
      Failed `CDLL(/opt/homebrew/lib/libgeos_c.dylib)`
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mq/m15w7rln2hncc1_q53ppfk5rkyh4qh/T/pip-install-htidmn92/shapely_6cf2b7dd59e745dca1ddcb1396ac009d/setup.py", line 74, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "/private/var/folders/mq/m15w7rln2hncc1_q53ppfk5rkyh4qh/T/pip-install-htidmn92/shapely_6cf2b7dd59e745dca1ddcb1396ac009d/shapely/_buildcfg.py", line 189, in <module>
          lgeos = load_dll('geos_c', fallbacks=alt_paths)
        File "/private/var/folders/mq/m15w7rln2hncc1_q53ppfk5rkyh4qh/T/pip-install-htidmn92/shapely_6cf2b7dd59e745dca1ddcb1396ac009d/shapely/_buildcfg.py", line 159, in load_dll
          raise OSError(
      OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib']

I already run python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git', but there still have this error.
Looking forward to your help

**Comment by jwyang** [comment]
it seems that you are trying to install it on windows? If it is, then we would recommend using a virtual machine or WSL with ubuntu system.
