### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Brush'

### ISSUE THREAD

**Issue by YangXuanyi** [microsoft/SoM#31]
Hello, I am very interested in your work. An error occurred while running `demo_som.py` after I installed the environment：
```
Traceback (most recent call last):
  File "/home/SoM_1/SoM/demo_som.py", line 132, in <module>
    image = gr.ImageMask(label="Input", type="pil", sources=["upload"], interactive=True, brush=gr.Brush(colors=["#FFFFFF"]))
AttributeError: module 'gradio' has no attribute 'Brush'
IMPORTANT: You are using gradio version 3.42.0, however version 4.29.0 is available, please upgrade.
--------
```

**After upgrading to the latest version of `gradio==4.29.0`, the program encountered:**

```

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 223, in push
    event_queue = self.event_queue_per_concurrency_id[event.concurrency_id]
KeyError: '22803346341552'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 713, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 729, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 775, in queue_join
    return await queue_join_helper(body, request, username)
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 793, in queue_join_helper
    success, event_id = await blocks._queue.push(
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 225, in push
    raise KeyError(
KeyError: 'Event not found in queue. If you are deploying this Gradio app with multiple replicas, please enable stickiness to ensure that all requests from the same user are routed to the same instance.'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 223, in push
    event_queue = self.event_queue_per_concurrency_id[event.concurrency_id]
KeyError: '22803346341552'
```
My environment is：
2080Ti
python 3.10
cuda 11.6

**Comment by YangXuanyi** [comment]
I have found a solution: `pip install gradio==4.24.0 `

**Comment by 944750720** [comment]
For me, gradio 4.24 doesn't work now. I used latest gradio 5.5.
![Image](https://github.com/user-attachments/assets/ad36d9b5-625b-4d6f-b0e5-89677d5cafca)
And my environment is:
Colab T4
python 3.10
cuda 12.2
![Image](https://github.com/user-attachments/assets/4b0b0560-b21f-4f3c-95ef-5696da63ea7b)
