### ISSUE TITLE
Failed with installing the SEEM library in Windows 10

### ISSUE THREAD

**Issue by Siu-Keung** [microsoft/SoM#47]
Hey guys,

I met the below error while installing the SEEM library in windows 10 OS:

######################################################
Collecting deepspeed==0.10.3 (from SEEM==1.0)
  Using cached deepspeed-0.10.3.tar.gz (867 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\usr\AppData\Local\Temp\pip-install-su14ddby\deepspeed_567f049e387d44dca824e1f320150964\setup.py", line 224, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\usr\AppData\Local\Temp\pip-install-su14ddby\deepspeed_567f049e387d44dca824e1f320150964\setup.py", line 216, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] Access is denied: '.\\deepspeed\\ops\\csrc'
      DS_BUILD_OPS=0
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
       [WARNING]  please install triton==1.0.0 if you want to use sparse attention
      Install Ops={'async_io': False, 'fused_adam': False, 'cpu_adam': False, 'cpu_adagrad': False, 'fused_lamb': False, 'quantizer': False, 'random_ltd': False, 'sparse_attn': False, 'spatial_inference': False, 'transformer': False, 'stochastic_transformer': False, 'transformer_inference': False}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
######################################################

Any ideas on fixing this issue? thx

**Comment by NielHung** [comment]
先设置
set DS_BUILD_AIO=0
set DS_BUILD_SPARSE_ATTN=0
set DS_BUILD_EVOFORMER_ATTN=0
set DS_BUILD_OPS=0
再安装
